---
name: PRs

on:
  push:
    branches: main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup go environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.16.2'
      - name: go vet
        run: go vet ./...
      - name: unit tests
        run: go test ./...
      - name: fmt
        run: test -z "$( gofmt -l -e -s $(find . -name '*.go') | tee /dev/stderr )"
      - name: build
        run: go build .
