---
name: Publish

on:
  push:
    branches:
      - "master"

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_NAME: "lfedge/adam"

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{env.IMAGE_NAME}}:${{github.sha}}
            ${{env.IMAGE_NAME}}:0.0.${{github.run_number}}
            ${{env.IMAGE_NAME}}:snapshot

