name: build

on:
  push:
    branches: main

env:
  IMAGE_NAME: lfedge/adam

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build
        run: go build .
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{env.IMAGE_NAME}}:${{env.GITHUB_SHA}}
            ${{env.IMAGE_NAME}}:0.0.${{env.GITHUB_RUN_NUMBER}}

